# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ax_pb2 as proto_dot_ax__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ax_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarnessServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/ax.HarnessService/Connect',
                request_serializer=proto_dot_ax__pb2.HarnessRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.HarnessResponse.FromString,
                _registered_method=True)


class HarnessServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Connect drives one harness execution. The client sends
        HarnessRequest{start} (and may send one HarnessRequest{cancel}
        mid-stream), and the server streams zero or more HarnessResponse{outputs}
        frames terminated by exactly one HarnessResponse{end}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=proto_dot_ax__pb2.HarnessRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.HarnessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.HarnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HarnessService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ax.HarnessService/Connect',
            proto_dot_ax__pb2.HarnessRequest.SerializeToString,
            proto_dot_ax__pb2.HarnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControllerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_stream(
                '/ax.ControllerService/Exec',
                request_serializer=proto_dot_ax__pb2.ExecRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ExecResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Exec executes an agentic task or resumes an existing one with streaming responses
        If the conversation_id already exists, it will be resumed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=proto_dot_ax__pb2.ExecRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ExecResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ax.ControllerService/Exec',
            proto_dot_ax__pb2.ExecRequest.SerializeToString,
            proto_dot_ax__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteConversation = channel.unary_unary(
                '/ax.ConversationService/DeleteConversation',
                request_serializer=proto_dot_ax__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.DeleteConversationResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DeleteConversation(self, request, context):
        """Deletes conversational events and all event log resources
        for its children executions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=proto_dot_ax__pb2.DeleteConversationRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.DeleteConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.ConversationService/DeleteConversation',
            proto_dot_ax__pb2.DeleteConversationRequest.SerializeToString,
            proto_dot_ax__pb2.DeleteConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
