// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/ax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of an execution
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

type AgentStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,2,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStart) Reset() {
	*x = AgentStart{}
	mi := &file_proto_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStart) ProtoMessage() {}

func (x *AgentStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStart.ProtoReflect.Descriptor instead.
func (*AgentStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStart) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *AgentStart) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOutputs) Reset() {
	*x = AgentOutputs{}
	mi := &file_proto_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOutputs) ProtoMessage() {}

func (x *AgentOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOutputs.ProtoReflect.Descriptor instead.
func (*AgentOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

func (x *AgentOutputs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnd) Reset() {
	*x = AgentEnd{}
	mi := &file_proto_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnd) ProtoMessage() {}

func (x *AgentEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnd.ProtoReflect.Descriptor instead.
func (*AgentEnd) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{2}
}

type AgentMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ExecId         string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*AgentMessage_Start
	//	*AgentMessage_Outputs
	//	*AgentMessage_End
	Type          isAgentMessage_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentMessage) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *AgentMessage) GetType() isAgentMessage_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgentMessage) GetStart() *AgentStart {
	if x != nil {
		if x, ok := x.Type.(*AgentMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AgentMessage) GetOutputs() *AgentOutputs {
	if x != nil {
		if x, ok := x.Type.(*AgentMessage_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

func (x *AgentMessage) GetEnd() *AgentEnd {
	if x != nil {
		if x, ok := x.Type.(*AgentMessage_End); ok {
			return x.End
		}
	}
	return nil
}

type isAgentMessage_Type interface {
	isAgentMessage_Type()
}

type AgentMessage_Start struct {
	Start *AgentStart `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type AgentMessage_Outputs struct {
	Outputs *AgentOutputs `protobuf:"bytes,4,opt,name=outputs,proto3,oneof"`
}

type AgentMessage_End struct {
	End *AgentEnd `protobuf:"bytes,5,opt,name=end,proto3,oneof"`
}

func (*AgentMessage_Start) isAgentMessage_Type() {}

func (*AgentMessage_Outputs) isAgentMessage_Type() {}

func (*AgentMessage_End) isAgentMessage_Type() {}

// Message is a message in the history.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // user, assistant, or model
	Content *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // content of the message
	// If true, the message is stored only in the execution log
	// (for resumption) but not in the conversation history,
	// and not emitted to the client or any agent.
	InternalOnly  bool `protobuf:"varint,3,opt,name=internal_only,json=internalOnly,proto3" json:"internal_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetInternalOnly() bool {
	if x != nil {
		return x.InternalOnly
	}
	return false
}

// A conversation is the historical session that consist of
// a number of execution. A conversation cannot be continued
// before the last execution is completed or failed.
type ConversationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ExecId         string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	State          State                  `protobuf:"varint,5,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationEvent) Reset() {
	*x = ConversationEvent{}
	mi := &file_proto_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEvent) ProtoMessage() {}

func (x *ConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEvent.ProtoReflect.Descriptor instead.
func (*ConversationEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConversationEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ConversationEvent) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

// ExecutionEvent is the entry in the event log. ExecutionEvents are used
// to record the actions taken place in the executor.
// The executor can replay the events for resumability.
type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   []byte                 `protobuf:"bytes,3,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Inputs        []*Message             `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*Message             `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	State         State                  `protobuf:"varint,6,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *ExecutionEvent) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecutionEvent) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecutionEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *ExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{7}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ExecRequest for executing.
type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Unique conversation identifier
	Inputs         []*Message             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                       // New inputs
	LastSeq        int32                  `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`                     // Last sequence number seen by the client
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                      // Agent ID, if empty planner is used
	AgentConfig    []byte                 `protobuf:"bytes,5,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`          // Agent configuration if any
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecRequest) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecRequest) GetLastSeq() int32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ExecRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecRequest) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

// ExecResponse contains the result of an execution.
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Message             `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Output content
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`        // Seq of the outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetOutputs() []*Message {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecResponse) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RemoteAgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // gRPC address for remote agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAgentConfig) Reset() {
	*x = RemoteAgentConfig{}
	mi := &file_proto_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAgentConfig) ProtoMessage() {}

func (x *RemoteAgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAgentConfig.ProtoReflect.Descriptor instead.
func (*RemoteAgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{11}
}

func (x *RemoteAgentConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RegisterAgentRequest for registering an agent
type RegisterAgentRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Human-readable name for the agent
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of agent capabilities
	Metadata    map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Config:
	//
	//	*RegisterAgentRequest_Remote
	Config        isRegisterAgentRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterAgentRequest) GetConfig() isRegisterAgentRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterAgentRequest) GetRemote() *RemoteAgentConfig {
	if x != nil {
		if x, ok := x.Config.(*RegisterAgentRequest_Remote); ok {
			return x.Remote
		}
	}
	return nil
}

type isRegisterAgentRequest_Config interface {
	isRegisterAgentRequest_Config()
}

type RegisterAgentRequest_Remote struct {
	Remote *RemoteAgentConfig `protobuf:"bytes,5,opt,name=remote,proto3,oneof"`
}

func (*RegisterAgentRequest_Remote) isRegisterAgentRequest_Config() {}

// RegisterAgentResponse contains registration result
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_ax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{13}
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_ax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{15}
}

type ForkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: The source conversation ID to fork from.
	SrcConversationId string `protobuf:"bytes,1,opt,name=src_conversation_id,json=srcConversationId,proto3" json:"src_conversation_id,omitempty"`
	// Optional: The sequence number to fork from.
	// Defaults to the latest sequence if not set or set to 0.
	SrcSeq int32 `protobuf:"varint,2,opt,name=src_seq,json=srcSeq,proto3" json:"src_seq,omitempty"`
	// Optional: The destination conversation ID.
	// Generates a new UUID if not provided.
	DestConversationId string `protobuf:"bytes,3,opt,name=dest_conversation_id,json=destConversationId,proto3" json:"dest_conversation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_proto_ax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{16}
}

func (x *ForkRequest) GetSrcConversationId() string {
	if x != nil {
		return x.SrcConversationId
	}
	return ""
}

func (x *ForkRequest) GetSrcSeq() int32 {
	if x != nil {
		return x.SrcSeq
	}
	return 0
}

func (x *ForkRequest) GetDestConversationId() string {
	if x != nil {
		return x.DestConversationId
	}
	return ""
}

type ForkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // The ID of the new conversation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForkResponse) Reset() {
	*x = ForkResponse{}
	mi := &file_proto_ax_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResponse) ProtoMessage() {}

func (x *ForkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResponse.ProtoReflect.Descriptor instead.
func (*ForkResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{17}
}

func (x *ForkResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

var File_proto_ax_proto protoreflect.FileDescriptor

const file_proto_ax_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ax.proto\x12\x02ax\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13proto/content.proto\"s\n" +
	"\n" +
	"AgentStart\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x02 \x01(\fR\vagentConfig\x12'\n" +
	"\bmessages\x18\x03 \x03(\v2\v.ax.MessageR\bmessages\"7\n" +
	"\fAgentOutputs\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.ax.MessageR\bmessages\"\n" +
	"\n" +
	"\bAgentEnd\"\xd0\x01\n" +
	"\fAgentMessage\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12&\n" +
	"\x05start\x18\x03 \x01(\v2\x0e.ax.AgentStartH\x00R\x05start\x12,\n" +
	"\aoutputs\x18\x04 \x01(\v2\x10.ax.AgentOutputsH\x00R\aoutputs\x12 \n" +
	"\x03end\x18\x05 \x01(\v2\f.ax.AgentEndH\x00R\x03endB\x06\n" +
	"\x04type\"i\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12%\n" +
	"\acontent\x18\x02 \x01(\v2\v.ax.ContentR\acontent\x12#\n" +
	"\rinternal_only\x18\x03 \x01(\bR\finternalOnly\"\xb1\x01\n" +
	"\x11ConversationEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\x12'\n" +
	"\bmessages\x18\x04 \x03(\v2\v.ax.MessageR\bmessages\x12\x1f\n" +
	"\x05state\x18\x05 \x01(\x0e2\t.ax.StateR\x05state\"\x8e\x02\n" +
	"\x0eExecutionEvent\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x03 \x01(\fR\vagentConfig\x12#\n" +
	"\x06inputs\x18\x04 \x03(\v2\v.ax.MessageR\x06inputs\x12%\n" +
	"\aoutputs\x18\x05 \x03(\v2\v.ax.MessageR\aoutputs\x12\x1f\n" +
	"\x05state\x18\x06 \x01(\x0e2\t.ax.StateR\x05state\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb4\x01\n" +
	"\vExecRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12#\n" +
	"\x06inputs\x18\x02 \x03(\v2\v.ax.MessageR\x06inputs\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x05R\alastSeq\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x05 \x01(\fR\vagentConfig\"G\n" +
	"\fExecResponse\x12%\n" +
	"\aoutputs\x18\x01 \x03(\v2\v.ax.MessageR\aoutputs\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\"-\n" +
	"\x11RemoteAgentConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xa3\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.ax.RegisterAgentRequest.MetadataEntryR\bmetadata\x12/\n" +
	"\x06remote\x18\x05 \x01(\v2\x15.ax.RemoteAgentConfigH\x00R\x06remote\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06config\"\x17\n" +
	"\x15RegisterAgentResponse\"8\n" +
	"\rDeleteRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x10\n" +
	"\x0eDeleteResponse\"\x88\x01\n" +
	"\vForkRequest\x12.\n" +
	"\x13src_conversation_id\x18\x01 \x01(\tR\x11srcConversationId\x12\x17\n" +
	"\asrc_seq\x18\x02 \x01(\x05R\x06srcSeq\x120\n" +
	"\x14dest_conversation_id\x18\x03 \x01(\tR\x12destConversationId\"7\n" +
	"\fForkResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId*X\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x032\x81\x01\n" +
	"\fAgentService\x121\n" +
	"\aConnect\x12\x10.ax.AgentMessage\x1a\x10.ax.AgentMessage(\x010\x01\x12>\n" +
	"\vHealthCheck\x12\x16.ax.HealthCheckRequest\x1a\x17.ax.HealthCheckResponse2\x86\x01\n" +
	"\x11ControllerService\x12+\n" +
	"\x04Exec\x12\x0f.ax.ExecRequest\x1a\x10.ax.ExecResponse0\x01\x12D\n" +
	"\rRegisterAgent\x12\x18.ax.RegisterAgentRequest\x1a\x19.ax.RegisterAgentResponse2\x85\x01\n" +
	"\x0fEventLogService\x12;\n" +
	"\x12DeleteConversation\x12\x11.ax.DeleteRequest\x1a\x12.ax.DeleteResponse\x125\n" +
	"\x10ForkConversation\x12\x0f.ax.ForkRequest\x1a\x10.ax.ForkResponseB\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_ax_proto_rawDescOnce sync.Once
	file_proto_ax_proto_rawDescData []byte
)

func file_proto_ax_proto_rawDescGZIP() []byte {
	file_proto_ax_proto_rawDescOnce.Do(func() {
		file_proto_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)))
	})
	return file_proto_ax_proto_rawDescData
}

var file_proto_ax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ax_proto_goTypes = []any{
	(State)(0),                    // 0: ax.State
	(*AgentStart)(nil),            // 1: ax.AgentStart
	(*AgentOutputs)(nil),          // 2: ax.AgentOutputs
	(*AgentEnd)(nil),              // 3: ax.AgentEnd
	(*AgentMessage)(nil),          // 4: ax.AgentMessage
	(*Message)(nil),               // 5: ax.Message
	(*ConversationEvent)(nil),     // 6: ax.ConversationEvent
	(*ExecutionEvent)(nil),        // 7: ax.ExecutionEvent
	(*HealthCheckRequest)(nil),    // 8: ax.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 9: ax.HealthCheckResponse
	(*ExecRequest)(nil),           // 10: ax.ExecRequest
	(*ExecResponse)(nil),          // 11: ax.ExecResponse
	(*RemoteAgentConfig)(nil),     // 12: ax.RemoteAgentConfig
	(*RegisterAgentRequest)(nil),  // 13: ax.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 14: ax.RegisterAgentResponse
	(*DeleteRequest)(nil),         // 15: ax.DeleteRequest
	(*DeleteResponse)(nil),        // 16: ax.DeleteResponse
	(*ForkRequest)(nil),           // 17: ax.ForkRequest
	(*ForkResponse)(nil),          // 18: ax.ForkResponse
	nil,                           // 19: ax.RegisterAgentRequest.MetadataEntry
	(*Content)(nil),               // 20: ax.Content
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_proto_ax_proto_depIdxs = []int32{
	5,  // 0: ax.AgentStart.messages:type_name -> ax.Message
	5,  // 1: ax.AgentOutputs.messages:type_name -> ax.Message
	1,  // 2: ax.AgentMessage.start:type_name -> ax.AgentStart
	2,  // 3: ax.AgentMessage.outputs:type_name -> ax.AgentOutputs
	3,  // 4: ax.AgentMessage.end:type_name -> ax.AgentEnd
	20, // 5: ax.Message.content:type_name -> ax.Content
	5,  // 6: ax.ConversationEvent.messages:type_name -> ax.Message
	0,  // 7: ax.ConversationEvent.state:type_name -> ax.State
	5,  // 8: ax.ExecutionEvent.inputs:type_name -> ax.Message
	5,  // 9: ax.ExecutionEvent.outputs:type_name -> ax.Message
	0,  // 10: ax.ExecutionEvent.state:type_name -> ax.State
	21, // 11: ax.ExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 12: ax.ExecRequest.inputs:type_name -> ax.Message
	5,  // 13: ax.ExecResponse.outputs:type_name -> ax.Message
	19, // 14: ax.RegisterAgentRequest.metadata:type_name -> ax.RegisterAgentRequest.MetadataEntry
	12, // 15: ax.RegisterAgentRequest.remote:type_name -> ax.RemoteAgentConfig
	4,  // 16: ax.AgentService.Connect:input_type -> ax.AgentMessage
	8,  // 17: ax.AgentService.HealthCheck:input_type -> ax.HealthCheckRequest
	10, // 18: ax.ControllerService.Exec:input_type -> ax.ExecRequest
	13, // 19: ax.ControllerService.RegisterAgent:input_type -> ax.RegisterAgentRequest
	15, // 20: ax.EventLogService.DeleteConversation:input_type -> ax.DeleteRequest
	17, // 21: ax.EventLogService.ForkConversation:input_type -> ax.ForkRequest
	4,  // 22: ax.AgentService.Connect:output_type -> ax.AgentMessage
	9,  // 23: ax.AgentService.HealthCheck:output_type -> ax.HealthCheckResponse
	11, // 24: ax.ControllerService.Exec:output_type -> ax.ExecResponse
	14, // 25: ax.ControllerService.RegisterAgent:output_type -> ax.RegisterAgentResponse
	16, // 26: ax.EventLogService.DeleteConversation:output_type -> ax.DeleteResponse
	18, // 27: ax.EventLogService.ForkConversation:output_type -> ax.ForkResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_ax_proto_init() }
func file_proto_ax_proto_init() {
	if File_proto_ax_proto != nil {
		return
	}
	file_proto_content_proto_init()
	file_proto_ax_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Start)(nil),
		(*AgentMessage_Outputs)(nil),
		(*AgentMessage_End)(nil),
	}
	file_proto_ax_proto_msgTypes[12].OneofWrappers = []any{
		(*RegisterAgentRequest_Remote)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_ax_proto_goTypes,
		DependencyIndexes: file_proto_ax_proto_depIdxs,
		EnumInfos:         file_proto_ax_proto_enumTypes,
		MessageInfos:      file_proto_ax_proto_msgTypes,
	}.Build()
	File_proto_ax_proto = out.File
	file_proto_ax_proto_goTypes = nil
	file_proto_ax_proto_depIdxs = nil
}
