// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: proto/gar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of a session
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gar_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_gar_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

// ProcessRequest is an input to an agent.
type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_proto_gar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

// ProcessResponse is an output from an agent.
// It can be returned in a streaming fashion.
type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Contents      []*Content             `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_gar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *ProcessResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ProcessResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// TextContent represents a text content.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_proto_gar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{2}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_proto_gar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type DeclineDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declined      bool                   `protobuf:"varint,1,opt,name=declined,proto3" json:"declined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDecision) Reset() {
	*x = DeclineDecision{}
	mi := &file_proto_gar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDecision) ProtoMessage() {}

func (x *DeclineDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDecision.ProtoReflect.Descriptor instead.
func (*DeclineDecision) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{4}
}

func (x *DeclineDecision) GetDeclined() bool {
	if x != nil {
		return x.Declined
	}
	return false
}

type ConfirmationContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Question string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	// Types that are valid to be assigned to Decision:
	//
	//	*ConfirmationContent_Approval
	//	*ConfirmationContent_Decline
	Decision      isConfirmationContent_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationContent) Reset() {
	*x = ConfirmationContent{}
	mi := &file_proto_gar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationContent) ProtoMessage() {}

func (x *ConfirmationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationContent.ProtoReflect.Descriptor instead.
func (*ConfirmationContent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmationContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmationContent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ConfirmationContent) GetDecision() isConfirmationContent_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ConfirmationContent) GetApproval() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *ConfirmationContent) GetDecline() *DeclineDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Decline); ok {
			return x.Decline
		}
	}
	return nil
}

type isConfirmationContent_Decision interface {
	isConfirmationContent_Decision()
}

type ConfirmationContent_Approval struct {
	Approval *ApprovalDecision `protobuf:"bytes,5,opt,name=approval,proto3,oneof"`
}

type ConfirmationContent_Decline struct {
	Decline *DeclineDecision `protobuf:"bytes,6,opt,name=decline,proto3,oneof"`
}

func (*ConfirmationContent_Approval) isConfirmationContent_Decision() {}

func (*ConfirmationContent_Decline) isConfirmationContent_Decision() {}

type FunctionCallContent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args             *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Id               string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ThoughtSignature []byte                 `protobuf:"bytes,4,opt,name=thought_signature,json=thoughtSignature,proto3" json:"thought_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FunctionCallContent) Reset() {
	*x = FunctionCallContent{}
	mi := &file_proto_gar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallContent) ProtoMessage() {}

func (x *FunctionCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallContent.ProtoReflect.Descriptor instead.
func (*FunctionCallContent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionCallContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallContent) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FunctionCallContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionCallContent) GetThoughtSignature() []byte {
	if x != nil {
		return x.ThoughtSignature
	}
	return nil
}

type FunctionResponseContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Response      *structpb.Struct       `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResponseContent) Reset() {
	*x = FunctionResponseContent{}
	mi := &file_proto_gar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResponseContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResponseContent) ProtoMessage() {}

func (x *FunctionResponseContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResponseContent.ProtoReflect.Descriptor instead.
func (*FunctionResponseContent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionResponseContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResponseContent) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FunctionResponseContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Content represents a message with role, type, mimetype, and data fields
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Content_Text
	//	*Content_Confirmation
	//	*Content_FunctionCall
	//	*Content_FunctionResponse
	Content       isContent_Content `protobuf_oneof:"content"`
	Role          string            `protobuf:"bytes,1000,opt,name=role,proto3" json:"role,omitempty"` // The role of the content (e.g., "user", "assistant", "system")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_gar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{8}
}

func (x *Content) GetContent() isContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Content) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetConfirmation() *ConfirmationContent {
	if x != nil {
		if x, ok := x.Content.(*Content_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *Content) GetFunctionCall() *FunctionCallContent {
	if x != nil {
		if x, ok := x.Content.(*Content_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Content) GetFunctionResponse() *FunctionResponseContent {
	if x != nil {
		if x, ok := x.Content.(*Content_FunctionResponse); ok {
			return x.FunctionResponse
		}
	}
	return nil
}

func (x *Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type isContent_Content interface {
	isContent_Content()
}

type Content_Text struct {
	Text *TextContent `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Content_Confirmation struct {
	Confirmation *ConfirmationContent `protobuf:"bytes,26,opt,name=confirmation,proto3,oneof"`
}

type Content_FunctionCall struct {
	FunctionCall *FunctionCallContent `protobuf:"bytes,27,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Content_FunctionResponse struct {
	FunctionResponse *FunctionResponseContent `protobuf:"bytes,28,opt,name=function_response,json=functionResponse,proto3,oneof"`
}

func (*Content_Text) isContent_Content() {}

func (*Content_Confirmation) isContent_Content() {}

func (*Content_FunctionCall) isContent_Content() {}

func (*Content_FunctionResponse) isContent_Content() {}

// ExecutionEvent is the entry in the event log. ExecutionEvents are used
// to record the actions taken place in the executor.
// The executor can replay the events for resumability.
type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Inputs        []*Content             `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*Content             `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	State         State                  `protobuf:"varint,6,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // string checkpoint_id = 10;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_proto_gar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecutionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionEvent) GetInputs() []*Content {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecutionEvent) GetOutputs() []*Content {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecutionEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *ExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_gar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{10}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_gar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TriggerSessionRequest for triggering a new session
type TriggerSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // Agent ID, if empty planner is used.
	Inputs        []*Content             `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`                        // Input content to process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionRequest) Reset() {
	*x = TriggerSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionRequest) ProtoMessage() {}

func (x *TriggerSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionRequest.ProtoReflect.Descriptor instead.
func (*TriggerSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TriggerSessionRequest) GetInputs() []*Content {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// TriggerSessionResponse contains the result of triggering a session
type TriggerSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID (in case it was generated or modified by server)
	Outputs       []*Content             `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`                      // Output content
	State         State                  `protobuf:"varint,3,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`        // Session state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionResponse) Reset() {
	*x = TriggerSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionResponse) ProtoMessage() {}

func (x *TriggerSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionResponse.ProtoReflect.Descriptor instead.
func (*TriggerSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionResponse) GetOutputs() []*Content {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TriggerSessionResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

type ForkSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SrcSessionId    string                 `protobuf:"bytes,1,opt,name=src_session_id,json=srcSessionId,proto3" json:"src_session_id,omitempty"`
	SrcCheckpointId string                 `protobuf:"bytes,2,opt,name=src_checkpoint_id,json=srcCheckpointId,proto3" json:"src_checkpoint_id,omitempty"` // Checkpoint ID within the source session to fork from.
	DestSessionId   string                 `protobuf:"bytes,3,opt,name=dest_session_id,json=destSessionId,proto3" json:"dest_session_id,omitempty"`       // New session ID. If provided, must not exist.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForkSessionRequest) Reset() {
	*x = ForkSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkSessionRequest) ProtoMessage() {}

func (x *ForkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkSessionRequest.ProtoReflect.Descriptor instead.
func (*ForkSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{14}
}

func (x *ForkSessionRequest) GetSrcSessionId() string {
	if x != nil {
		return x.SrcSessionId
	}
	return ""
}

func (x *ForkSessionRequest) GetSrcCheckpointId() string {
	if x != nil {
		return x.SrcCheckpointId
	}
	return ""
}

func (x *ForkSessionRequest) GetDestSessionId() string {
	if x != nil {
		return x.DestSessionId
	}
	return ""
}

type ForkSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSessionId  string                 `protobuf:"bytes,1,opt,name=new_session_id,json=newSessionId,proto3" json:"new_session_id,omitempty"` // New session ID (in case it was generated or modified by server)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkSessionResponse) Reset() {
	*x = ForkSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkSessionResponse) ProtoMessage() {}

func (x *ForkSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkSessionResponse.ProtoReflect.Descriptor instead.
func (*ForkSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{15}
}

func (x *ForkSessionResponse) GetNewSessionId() string {
	if x != nil {
		return x.NewSessionId
	}
	return ""
}

type RemoteAgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // gRPC address for remote agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAgentConfig) Reset() {
	*x = RemoteAgentConfig{}
	mi := &file_proto_gar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAgentConfig) ProtoMessage() {}

func (x *RemoteAgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAgentConfig.ProtoReflect.Descriptor instead.
func (*RemoteAgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{16}
}

func (x *RemoteAgentConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RegisterAgentRequest for registering an agent
type RegisterAgentRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Human-readable name for the agent
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of agent capabilities
	Metadata    map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Config:
	//
	//	*RegisterAgentRequest_Remote
	Config        isRegisterAgentRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterAgentRequest) GetConfig() isRegisterAgentRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterAgentRequest) GetRemote() *RemoteAgentConfig {
	if x != nil {
		if x, ok := x.Config.(*RegisterAgentRequest_Remote); ok {
			return x.Remote
		}
	}
	return nil
}

type isRegisterAgentRequest_Config interface {
	isRegisterAgentRequest_Config()
}

type RegisterAgentRequest_Remote struct {
	Remote *RemoteAgentConfig `protobuf:"bytes,5,opt,name=remote,proto3,oneof"`
}

func (*RegisterAgentRequest_Remote) isRegisterAgentRequest_Config() {}

// RegisterAgentResponse contains registration result
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{18}
}

// UnregisterAgentRequest for unregistering an agent
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{19}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// UnregisterAgentResponse contains unregistration result
type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{20}
}

var File_proto_gar_proto protoreflect.FileDescriptor

const file_proto_gar_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gar.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"<\n" +
	"\x0eProcessRequest\x12*\n" +
	"\bcontents\x18\x01 \x03(\v2\x0e.proto.ContentR\bcontents\"\x81\x01\n" +
	"\x0fProcessResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12*\n" +
	"\bcontents\x18\x02 \x03(\v2\x0e.proto.ContentR\bcontents\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\"3\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\".\n" +
	"\x10ApprovalDecision\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\";\n" +
	"\x0fDeclineDecision\x12\x1a\n" +
	"\bdeclined\x18\x01 \x01(\bR\bdeclinedJ\x04\b\x02\x10\x03R\x06reason\"\xca\x01\n" +
	"\x13ConfirmationContent\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x125\n" +
	"\bapproval\x18\x05 \x01(\v2\x17.proto.ApprovalDecisionH\x00R\bapproval\x122\n" +
	"\adecline\x18\x06 \x01(\v2\x16.proto.DeclineDecisionH\x00R\adeclineB\n" +
	"\n" +
	"\bdecisionJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\"\x93\x01\n" +
	"\x13FunctionCallContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12+\n" +
	"\x11thought_signature\x18\x04 \x01(\fR\x10thoughtSignature\"r\n" +
	"\x17FunctionResponseContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bresponse\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xb9\x02\n" +
	"\aContent\x12(\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x12.proto.TextContentH\x00R\x04text\x12@\n" +
	"\fconfirmation\x18\x1a \x01(\v2\x1a.proto.ConfirmationContentH\x00R\fconfirmation\x12A\n" +
	"\rfunction_call\x18\x1b \x01(\v2\x1a.proto.FunctionCallContentH\x00R\ffunctionCall\x12M\n" +
	"\x11function_response\x18\x1c \x01(\v2\x1e.proto.FunctionResponseContentH\x00R\x10functionResponse\x12\x13\n" +
	"\x04role\x18\xe8\a \x01(\tR\x04roleB\t\n" +
	"\acontentJ\x04\b\x01\x10\x05J\x04\b\x06\x10\n" +
	"J\x04\b\v\x10\x1a\"\xf4\x01\n" +
	"\x0eExecutionEvent\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12&\n" +
	"\x06inputs\x18\x04 \x03(\v2\x0e.proto.ContentR\x06inputs\x12(\n" +
	"\aoutputs\x18\x05 \x03(\v2\x0e.proto.ContentR\aoutputs\x12\"\n" +
	"\x05state\x18\x06 \x01(\x0e2\f.proto.StateR\x05state\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x15TriggerSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12&\n" +
	"\x06inputs\x18\x03 \x03(\v2\x0e.proto.ContentR\x06inputs\"\x85\x01\n" +
	"\x16TriggerSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\aoutputs\x18\x02 \x03(\v2\x0e.proto.ContentR\aoutputs\x12\"\n" +
	"\x05state\x18\x03 \x01(\x0e2\f.proto.StateR\x05state\"\x8e\x01\n" +
	"\x12ForkSessionRequest\x12$\n" +
	"\x0esrc_session_id\x18\x01 \x01(\tR\fsrcSessionId\x12*\n" +
	"\x11src_checkpoint_id\x18\x02 \x01(\tR\x0fsrcCheckpointId\x12&\n" +
	"\x0fdest_session_id\x18\x03 \x01(\tR\rdestSessionId\";\n" +
	"\x13ForkSessionResponse\x12$\n" +
	"\x0enew_session_id\x18\x01 \x01(\tR\fnewSessionId\"-\n" +
	"\x11RemoteAgentConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xa9\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).proto.RegisterAgentRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06remote\x18\x05 \x01(\v2\x18.proto.RemoteAgentConfigH\x00R\x06remote\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06config\"\x17\n" +
	"\x15RegisterAgentResponse\"3\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x19\n" +
	"\x17UnregisterAgentResponse*X\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x032\x92\x01\n" +
	"\fAgentService\x12<\n" +
	"\aProcess\x12\x15.proto.ProcessRequest\x1a\x16.proto.ProcessResponse(\x010\x01\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse2\xc1\x02\n" +
	"\n" +
	"GARService\x12O\n" +
	"\x0eTriggerSession\x12\x1c.proto.TriggerSessionRequest\x1a\x1d.proto.TriggerSessionResponse0\x01\x12D\n" +
	"\vForkSession\x12\x19.proto.ForkSessionRequest\x1a\x1a.proto.ForkSessionResponse\x12J\n" +
	"\rRegisterAgent\x12\x1b.proto.RegisterAgentRequest\x1a\x1c.proto.RegisterAgentResponse\x12P\n" +
	"\x0fUnregisterAgent\x12\x1d.proto.UnregisterAgentRequest\x1a\x1e.proto.UnregisterAgentResponseB\x1dZ\x1bgithub.com/google/gar/protob\x06proto3"

var (
	file_proto_gar_proto_rawDescOnce sync.Once
	file_proto_gar_proto_rawDescData []byte
)

func file_proto_gar_proto_rawDescGZIP() []byte {
	file_proto_gar_proto_rawDescOnce.Do(func() {
		file_proto_gar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)))
	})
	return file_proto_gar_proto_rawDescData
}

var file_proto_gar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gar_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_gar_proto_goTypes = []any{
	(State)(0),                      // 0: proto.State
	(*ProcessRequest)(nil),          // 1: proto.ProcessRequest
	(*ProcessResponse)(nil),         // 2: proto.ProcessResponse
	(*TextContent)(nil),             // 3: proto.TextContent
	(*ApprovalDecision)(nil),        // 4: proto.ApprovalDecision
	(*DeclineDecision)(nil),         // 5: proto.DeclineDecision
	(*ConfirmationContent)(nil),     // 6: proto.ConfirmationContent
	(*FunctionCallContent)(nil),     // 7: proto.FunctionCallContent
	(*FunctionResponseContent)(nil), // 8: proto.FunctionResponseContent
	(*Content)(nil),                 // 9: proto.Content
	(*ExecutionEvent)(nil),          // 10: proto.ExecutionEvent
	(*HealthCheckRequest)(nil),      // 11: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 12: proto.HealthCheckResponse
	(*TriggerSessionRequest)(nil),   // 13: proto.TriggerSessionRequest
	(*TriggerSessionResponse)(nil),  // 14: proto.TriggerSessionResponse
	(*ForkSessionRequest)(nil),      // 15: proto.ForkSessionRequest
	(*ForkSessionResponse)(nil),     // 16: proto.ForkSessionResponse
	(*RemoteAgentConfig)(nil),       // 17: proto.RemoteAgentConfig
	(*RegisterAgentRequest)(nil),    // 18: proto.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 19: proto.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),  // 20: proto.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 21: proto.UnregisterAgentResponse
	nil,                             // 22: proto.RegisterAgentRequest.MetadataEntry
	(*structpb.Struct)(nil),         // 23: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
}
var file_proto_gar_proto_depIdxs = []int32{
	9,  // 0: proto.ProcessRequest.contents:type_name -> proto.Content
	9,  // 1: proto.ProcessResponse.contents:type_name -> proto.Content
	4,  // 2: proto.ConfirmationContent.approval:type_name -> proto.ApprovalDecision
	5,  // 3: proto.ConfirmationContent.decline:type_name -> proto.DeclineDecision
	23, // 4: proto.FunctionCallContent.args:type_name -> google.protobuf.Struct
	23, // 5: proto.FunctionResponseContent.response:type_name -> google.protobuf.Struct
	3,  // 6: proto.Content.text:type_name -> proto.TextContent
	6,  // 7: proto.Content.confirmation:type_name -> proto.ConfirmationContent
	7,  // 8: proto.Content.function_call:type_name -> proto.FunctionCallContent
	8,  // 9: proto.Content.function_response:type_name -> proto.FunctionResponseContent
	9,  // 10: proto.ExecutionEvent.inputs:type_name -> proto.Content
	9,  // 11: proto.ExecutionEvent.outputs:type_name -> proto.Content
	0,  // 12: proto.ExecutionEvent.state:type_name -> proto.State
	24, // 13: proto.ExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 14: proto.TriggerSessionRequest.inputs:type_name -> proto.Content
	9,  // 15: proto.TriggerSessionResponse.outputs:type_name -> proto.Content
	0,  // 16: proto.TriggerSessionResponse.state:type_name -> proto.State
	22, // 17: proto.RegisterAgentRequest.metadata:type_name -> proto.RegisterAgentRequest.MetadataEntry
	17, // 18: proto.RegisterAgentRequest.remote:type_name -> proto.RemoteAgentConfig
	1,  // 19: proto.AgentService.Process:input_type -> proto.ProcessRequest
	11, // 20: proto.AgentService.HealthCheck:input_type -> proto.HealthCheckRequest
	13, // 21: proto.GARService.TriggerSession:input_type -> proto.TriggerSessionRequest
	15, // 22: proto.GARService.ForkSession:input_type -> proto.ForkSessionRequest
	18, // 23: proto.GARService.RegisterAgent:input_type -> proto.RegisterAgentRequest
	20, // 24: proto.GARService.UnregisterAgent:input_type -> proto.UnregisterAgentRequest
	2,  // 25: proto.AgentService.Process:output_type -> proto.ProcessResponse
	12, // 26: proto.AgentService.HealthCheck:output_type -> proto.HealthCheckResponse
	14, // 27: proto.GARService.TriggerSession:output_type -> proto.TriggerSessionResponse
	16, // 28: proto.GARService.ForkSession:output_type -> proto.ForkSessionResponse
	19, // 29: proto.GARService.RegisterAgent:output_type -> proto.RegisterAgentResponse
	21, // 30: proto.GARService.UnregisterAgent:output_type -> proto.UnregisterAgentResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_gar_proto_init() }
func file_proto_gar_proto_init() {
	if File_proto_gar_proto != nil {
		return
	}
	file_proto_gar_proto_msgTypes[5].OneofWrappers = []any{
		(*ConfirmationContent_Approval)(nil),
		(*ConfirmationContent_Decline)(nil),
	}
	file_proto_gar_proto_msgTypes[8].OneofWrappers = []any{
		(*Content_Text)(nil),
		(*Content_Confirmation)(nil),
		(*Content_FunctionCall)(nil),
		(*Content_FunctionResponse)(nil),
	}
	file_proto_gar_proto_msgTypes[17].OneofWrappers = []any{
		(*RegisterAgentRequest_Remote)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gar_proto_goTypes,
		DependencyIndexes: file_proto_gar_proto_depIdxs,
		EnumInfos:         file_proto_gar_proto_enumTypes,
		MessageInfos:      file_proto_gar_proto_msgTypes,
	}.Build()
	File_proto_gar_proto = out.File
	file_proto_gar_proto_goTypes = nil
	file_proto_gar_proto_depIdxs = nil
}
